'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class OOPegitimkampi_EntityfwtraveldbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=OOPegitimkampi_EntityfwtraveldbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Admin() As DbSet(Of Admin)
    Public Overridable Property Customer() As DbSet(Of Customer)
    Public Overridable Property Guide() As DbSet(Of Guide)
    Public Overridable Property Location() As DbSet(Of Location)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)

End Class
