'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Guide
    Public Property GuideId As Integer
    Public Property GuideName As String
    Public Property GuideSurname As String

    Public Overridable Property Location As ICollection(Of Location) = New HashSet(Of Location)

End Class
